/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as BuildersIndexRouteImport } from './routes/builders/index'
import { Route as BuildersProjectsRouteImport } from './routes/builders/projects'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as CommunitiesCertifiedRouteImport } from './routes/communities/certified'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIndexRoute = BuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersProjectsRoute = BuildersProjectsRouteImport.update({
  id: '/builders/projects',
  path: '/builders/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCertifiedRoute = CommunitiesCertifiedRouteImport.update({
  id: '/communities/certified',
  path: '/communities/certified',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/builders/projects': typeof BuildersProjectsRoute
  '/communities/certified': typeof CommunitiesCertifiedRoute
  '/builders/': typeof BuildersIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/builders/projects': typeof BuildersProjectsRoute
  '/communities/certified': typeof CommunitiesCertifiedRoute
  '/builders': typeof BuildersIndexRoute
  '/communities': typeof CommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/programs': typeof ProgramsRoute
  '/builders/projects': typeof BuildersProjectsRoute
  '/communities/certified': typeof CommunitiesCertifiedRoute
  '/builders/': typeof BuildersIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/programs'
    | '/builders/projects'
    | '/communities/certified'
    | '/builders/'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/programs'
    | '/builders/projects'
    | '/communities/certified'
    | '/builders'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/programs'
    | '/builders/projects'
    | '/communities/certified'
    | '/builders/'
    | '/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProgramsRoute: typeof ProgramsRoute
  BuildersProjectsRoute: typeof BuildersProjectsRoute
  CommunitiesCertifiedRoute: typeof CommunitiesCertifiedRoute
  BuildersIndexRoute: typeof BuildersIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/': {
      id: '/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof BuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/projects': {
      id: '/builders/projects'
      path: '/builders/projects'
      fullPath: '/builders/projects'
      preLoaderRoute: typeof BuildersProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/certified': {
      id: '/communities/certified'
      path: '/communities/certified'
      fullPath: '/communities/certified'
      preLoaderRoute: typeof CommunitiesCertifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProgramsRoute: ProgramsRoute,
  BuildersProjectsRoute: BuildersProjectsRoute,
  CommunitiesCertifiedRoute: CommunitiesCertifiedRoute,
  BuildersIndexRoute: BuildersIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
